### ISSUE TITLE
[BUG] listSecrets() returns only the first page

### ISSUE THREAD

**Issue by afirth** [fugue/credstash#109]
If Table.scan would return more than 1MB, the result is paginated.
LastEvaluatedKey is set and scan() should be called again. 

[relevant credstash code link](https://github.com/fugue/credstash/blob/8ded48aa25f9ed80930bcbaba96bb5301bc31ae4/credstash.py#L211)
[boto docs](http://boto3.readthedocs.io/en/latest/reference/services/dynamodb.html#DynamoDB.Table.scan)
[aws docs](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/QueryAndScan.html#Pagination)

**Comment by williamsbdev** [comment]
We have also hit this issue. How do we get fix from @nathan-muir merged in?

**Comment by glyph** [comment]
I take it this also affects the command-line `credstash list`?

**Comment by williamsbdev** [comment]
@glyph - correct. That is actually where we first noticed the issue.

**Comment by glyph** [comment]
Pinging @alex-luminal since that worked for #158 - please let me know if this is annoying :-).

**Comment by glyph** [comment]
Was this resolved by #163?

**Comment by glyph** [comment]
cc @pm990320

**Comment by pm990320** [comment]
Yep this was the issue I encountered that #163 fixes

**Comment by glyph** [comment]
@alex-luminal can a repo owner close please?
