### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by trueseong** [fugue/credstash#113]
Hi there,
I've been looking for a tool like this or vault to manage the secrets for web applications. 
It looks to be pretty popular and great tool.  The one question I have is:
How do applications access the secrets using credstash?  
Since this is a script to access the dynamoDb and KMS to do the functional requirements, application won't be using API to get the secrets... What's the best or recommended approach to expose the secrets to the applications?

Thanks,

**Comment by alex-luminal** [comment]
some people use import credstash as a library into their application (and there are many projects out there that are ports of credstash to other languages if your application isn't in python; there are ports in PHP, javascript, golang, and several other languages).

Another very popular approach is to call credstash in your service startup script and put the secret in an env variable that your application can then access. So, for example,

```
export DB_PASSWORD=$(credstash get database.prod.password)
./startMyApplication.sh
```

or whatever

**Comment by trueseong** [comment]
make sense.. Thanks.
