### ISSUE TITLE
Add Links to other languages

### ISSUE THREAD

**Issue by pzb** [fugue/credstash#118]
There are several projects that provide credstash compatibility with other languages.  These should be acknowleged & linked from the README:

- https://github.com/jessecoyle/jcredstash (Java)
- https://github.com/adorechic/rcredstash (Ruby)
- https://github.com/kdrakon/scala-credstash (Scala)
- https://github.com/gmo/credstash-php (PHP)
- https://github.com/roylines/node-credstash (Node.js)
- https://github.com/winebarrel/gcredstash (Go)

**Comment by alex-luminal** [comment]
thanks for the ticket! addressed in #120
