### ISSUE TITLE
KMS Master Key Rotation

### ISSUE THREAD

**Issue by ervoiox** [fugue/credstash#123]
Hi,

Does credstash support the AWS option for automatic KMS Master Key rotation or does it expect the master key to not change?

Thanks!

**Comment by alex-luminal** [comment]
It should Just Work.

**Comment by alex-luminal** [comment]
KMS key rotation should be transparent to callers (KMS itself figures out what CMK to use for decryption, and uses the latest for encryption).

I'm going to close this for now, If you run into issues with this, feel free to reopen!

**Comment by ervoiox** [comment]
Awesome thanks!
