### ISSUE TITLE
Alternate implementations

### ISSUE THREAD

**Issue by adamhathcock** [fugue/credstash#127]
Hi all.

I've implemented a C# that is intended to just read the values for deployed .NET Core applications: https://github.com/Narochno/Narochno.Credstash

I don't intend to recreate everything the CLI does but I want to make sure I remain compatible.  Just wondering if there's anything upcoming to know.

Thanks for providing a good way to deal with secrets and AWS

**Comment by alex-luminal** [comment]
Awesome! I'll add a link in the readme.

The only think that might affect you in the medium-term is that we'll probably move to non-1 nonces. It'll be a PR that we leave open for a few days to make sure its visible. 

Don't know when that work will actually get done (PR's welcome :) ), but I know that its coming at _some point_

**Comment by alex-luminal** [comment]
going to close this for now, but dont be a stranger if you need something!

**Comment by adamhathcock** [comment]
Thanks!  I'll keep an eye on everything.
