### ISSUE TITLE
Request for a changelog

### ISSUE THREAD

**Issue by jinesh-choksi** [fugue/credstash#128]
We started using credstash last year and our automation for installing it failed after the move from PyCrypto to cryptography. ([link](https://github.com/fugue/credstash/commit/f039c63a07dd30cecdc0e6a93b3c9ae0713418c7))

To be able to quickly identify what has changed, recently would it be possible to keep a CHANGELOG.md file at the root of this repo?

Thanks.

**Comment by sid137** [comment]
@jinesh-choksi   Ahh...  so that's what happened..  i'm having the same issue...  it broke my CI pipeline..  thanks for the link

**Comment by alex-luminal** [comment]
We have release notes here: https://github.com/fugue/credstash/releases
I didnt realize that the move to cryptography changed linux reqs until two patch releases later, so that wouldn't have helped in this specific situation. 

Other than what's in the release notes, what other sorts of things would be useful in a changes file? I'm happy to put on in, I just want to make sure we don't just end up with two sets of release notes.

**Comment by jinesh-choksi** [comment]
>Other than what's in the release notes, what other sorts of things would be useful in a changes file?

- A benefit of the changelog file is that it would be under source control and available for review when you've downloaded the source code. The release notes seem to be a Github specific thing and I couldn't find their contents in the downloaded source.

- If the change was made because of a PR or Github issue then a link to that would be useful as part of the change log message as we can then look up the history behind it.


> I'm happy to put on in, I just want to make sure we don't just end up with two sets of release notes.

You can automate the process of generating the changelog:

- https://github.com/vaab/gitchangelog   (Python)
- https://github.com/skywinder/github-changelog-generator

Note: I haven't used the above but a brief scan shows they work off the git commit log.

Thanks.

**Comment by alex-luminal** [comment]
I'll leave this ticket open until we get the file in. We'll add a changelog file on the next release.

Thanks!

**Comment by gene1wood** [comment]
I've found [these guidlines](http://keepachangelog.com/) very useful in the past when creating changelogs.

**Comment by alex-luminal** [comment]
we have a changelog now! closing

**Comment by gene1wood** [comment]
[Changelog](https://github.com/fugue/credstash/blob/master/changelog.md) added in d7eba3007ad6a7d81e96f1b463114e5fb875b9a5
