### ISSUE TITLE
How to find the context of a key?

### ISSUE THREAD

**Issue by tchia04** [fugue/credstash#130]
When I use "credstash get" on a key it gave me the following
credstash get myapp.db2.prod
KMS ERROR: Could not decrypt hmac key with KMS. The encryption context provided may not match the one used when the credential was stored.

credstash list doesn't show the context either
credstash list
myapp.db.prod    -- version 0000000000000000000
myapp.db.prod    -- version 0000000000000000001
myapp.db.staging -- version 0000000000000000000
myapp.db2.prod   -- version 0000000000000000000

So if I forgot about the context, where can I look it up?

**Comment by alex-luminal** [comment]
credstash doesn't store the context. you need to either have it be something that's determined by what data you're looking up (for example, if you're encrypting an EBS volume, the context could be the volume-id), or you need to store it.

**Comment by alex-luminal** [comment]
going to close this. Feel free to re-open if you aren't set.

**Comment by gandonov** [comment]
Whooa fancy to see you here, Alex
