### ISSUE TITLE
[Question]: Slowness on credstash getall

### ISSUE THREAD

**Issue by thebenwaters** [fugue/credstash#142]
Hi here's our credstash setup

DynamoDB with 38 items, 17.13 KB

Provisioned read capacity units	1
Provisioned write capacity units	1

The Table is in us-west-2 (aka oregon). We are in Tel Aviv, Israel.

Our average time to run credstash getall takes around a minute and a half. Is there anyway to speed this up? Increase read capacity?

Or is it a the decrypt/encrypt that takes the time?

**Comment by alex-luminal** [comment]
the limiter here is your DDB read capacity. Dial that up some. 25 is still in the free tier. Past that you'll pay for it, buts its pretty cheap.

**Comment by thebenwaters** [comment]
Perfect thank you :)

**Comment by thebenwaters** [comment]
significant increase in performance

0.81s user 0.17s system 11% cpu 8.810 total
