### ISSUE TITLE
Unable to supply kms_key to getSecret

### ISSUE THREAD

**Issue by jonnyshaw89** [fugue/credstash#146]
Currently you are able to supply a `kms_key` when putting a key but are not able to supply the `kms_key` when getting the key with `getSecret()`

This means that you are able to add a key that you are not able to retrieve through this client.

**Comment by jonnyshaw89** [comment]
@alex-luminal This is a pretty big gap if you want to use multiple KMS keys. 
Could you look at the PR referenced?

**Comment by alex-luminal** [comment]
You don't need to pass a key to `getSecret()`. The ciphertext blob that gets sent to KMS includes a reference to the CMK that's needed to do the decryption. You only need to decide what KMS CMK to use for `encrypt` and then `decrypt` will just work.
