### ISSUE TITLE
error when trying to get credentials

### ISSUE THREAD

**Issue by sudharsans** [fugue/credstash#150]
Could some please help? I get the below error when trying to get.

$credstash -t test-table put -k alias/test-key test supersecretpassword1234
test has been stored

$credstash -t test-table get -k alias/test-key test 
credstash get: error: argument context: 'test' is not the form of "key=value"

**Comment by alex-luminal** [comment]
ditch the ` -k alias/test-key `

**Comment by sudharsans** [comment]
Thank you for the swift reply. it worked :)
