### ISSUE TITLE
Specify different KMS key

### ISSUE THREAD

**Issue by benfoster** [fugue/credstash#151]
How can I specify a different KMS key alias to be used instead of the default credstash one?

**Comment by benfoster** [comment]
Figured out I can specify the `-k` parameter when storing a credential.

**Comment by sunshine69** [comment]
Option -k does not exist any more. How could you work around this?

**Comment by alex-luminal** [comment]
yes it does: https://github.com/fugue/credstash/blob/master/credstash.py#L826
