### ISSUE TITLE
pkg_resources.DistributionNotFound: boto3>=1.1.1

### ISSUE THREAD

**Issue by rlauer6** [fugue/credstash#156]
Seems like this is telling me I don't have the correct version of boto3 library, but:
__version__ = '1.4.4'

What am I doing wrong?

rlauer@centos6 ~]$ sudo credstash setup
Traceback (most recent call last):
  File "/usr/bin/credstash", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: boto3>=1.1.1

**Comment by swibowo** [comment]
@rlauer6, I just encountered the same issue. What I found, the issue wasn't on boto3 but on cryptography. When you ran `pip install cryptography`, you most likely pulled in >2.x. Currently, credstash requires cryptography<2.0,>=1.5. 

> pkg_resources.DistributionNotFound: The 'cryptography<2.0,>=1.5' distribution was not found and is required by credstash

Try downgrading cryptography to 1.5.x. It worked for me.
