### ISSUE TITLE
please release so that cryptography can be updated

### ISSUE THREAD

**Issue by glyph** [fugue/credstash#158]
Since https://github.com/fugue/credstash/commit/d3c764ff3d7a61b12118d8e559f121ae72220602 is not present in any released version, it's not impossible to upgrade Cryptography (which contains critical security updates since it ships its own bundled OpenSSL) on projects using Credstash, without adding a `git+...` URL to requirements.txt. Please do a release to PyPI at your earliest convenience.  Thank you!

**Comment by glyph** [comment]
@alex-luminal Ping? Anything I can do to help move this along?

**Comment by alex-luminal** [comment]
done!

**Comment by glyph** [comment]
Thanks!
