### ISSUE TITLE
Deprecation warnings from deprecated hashes

### ISSUE THREAD

**Issue by alexharv074** [fugue/credstash#165]
Just recently I started getting these deprecation warnings:

```
[ec2-user@jenkins ~]$ credstash -h
/usr/bin/credstash.py:55: DeprecationWarning: The RIPEMD160 hash was deprecated in version 1.9.
  'RIPEMD': hashes.RIPEMD160,
/usr/bin/credstash.py:56: DeprecationWarning: The Whirlpool hash was deprecated in version 1.9.
  'WHIRLPOOL': hashes.Whirlpool,
...
```

These have been removed from the cryptography library see:
https://github.com/pyca/cryptography/blob/4c41ab087d4fa741ced2a8aba6fd38b20137f42b/CHANGELOG.rst#id1

**Comment by mblakele** [comment]
Today cryptography 2.1 removed these deprecated hashes. I'm not sure why, but this means credstash users have to pin cryptography to an earlier release, eg `cryptography==2.0.3`
