### ISSUE TITLE
Ability to specify custom CA bundle on command line

### ISSUE THREAD

**Issue by jpmaglutac** [fugue/credstash#166]
My organization uses a transparent HTTPS proxy that has overrides all certificates with a custom CA, so adding such an option would be quite useful. Boto3 and the AWS CLI both have this option so I imagine it should be possible?

**Comment by artburkart** [comment]
@jpmaglutac - If I'm not mistaken, credstash already supports the `AWS_CA_BUNDLE` environment variable. Have you tried it?

**Comment by jpmaglutac** [comment]
You're right, it does work! My bad for not checking the documentation in-depth enough. Thanks for the help!
