### ISSUE TITLE
Unable to import credstash module within python lambda function

### ISSUE THREAD

**Issue by mfisher29** [fugue/credstash#169]
Hello,

I'm trying to import credstash into a python lambda function like so:
`import credstash`

and access a secret:
`credstash.getSecret('bla')`

And I get the following error upon invocation of the lambda:
`Unable to import module 'ec_lambda_adx_scanner': /var/task/cryptography/hazmat/bindings/_constant_time.so: invalid ELF header`

ec_lambda_adx_scanner is my lambda function name. I'm not running in a virtual env, just deploying and invoking as usual from AWS.

Thank you in advance.

EDIT:
To give you a little more information, I am first installing credstash from a requirements.txt file via a shell script. This builds credstash locally on my Mac. I then use serverless to package up the lambdas and their dependencies and deploy. I believe the issue is that I have built a version of credstash for my Mac environment, but when I try to use that same build on lambda (Linux image) it fails.

Update: I rebuilt the credstash lib on a Linux EC2 AMI instance rather than on my mac and have now been receiving this error instead (seems to be another C lib.):
`Unable to import module 'ec_lambda_adx_scanner': libffi-a7faab9c.so.6.0.4: cannot open shared object file: No such file or directory`

**Comment by gyermolenko** [comment]
@mfisher29 have you tried to downgrade to credstash 1.12? You problem (and I got a similar one) could be cause by this change `removed build constraint on cryptography <2.0` in 1.13.3

**Comment by mfisher29** [comment]
I figured it out. I needed to build credstash on an EC2 AMI Image in a virtual env and then copy it back to my local directory so that  I could zip it up with the lambda and deploy to AWS.

Similar to these steps here:https://github.com/kiddouk/letslambda

Except with credstash 1.13.3 in the requirements.txt file instead.
