### ISSUE TITLE
Possible to store credstash variables in more than one DynamoDB instance?

### ISSUE THREAD

**Issue by mfisher29** [fugue/credstash#186]
Hi, 

I'm wondering if it's possible to store credstash credentials in more than one dynamoDB instance? Every variable my team has created is stored in one database, however the read capacity unit requirements are different for some variables as opposed to others. It is not cost effective to increase the dynamo read capacity of the whole instance when only one variable is accessed at high frequencies.

Is there a work around for this?

Thanks,
Marissa

**Comment by alex-luminal** [comment]
it won't be automatic or seamless, but you can use the `-t` flag to point credstash at a different table.
