### ISSUE TITLE
Option -k <key_name> no longer exists

### ISSUE THREAD

**Issue by sunshine69** [fugue/credstash#188]
Hi,

When I tried to use option -k <key_name_other_than_credstash> to put some credential and I got error.

credstash -p dpe_non_prod --key cloudwatch_feeder  put testme testvalue
usage: credstash [-h] [-r REGION] [-t TABLE] [-p PROFILE | -n ARN]
                 {delete,get,getall,keys,list,put,putall,setup} ...
credstash: error: invalid choice: 'cloudwatch_feeder' (choose from 'delete', 'get', 'getall', 'keys', 'list', 'put', 'putall', 'setup')

Same if I use short opt  -k 

Is it a bug or the support for that option is dropped?

Thanks

**Comment by alex-luminal** [comment]
`--key` is an option for the `put` command. you need to do 
`credstash -p dpe_non_prod put --key cloudwatch_feeder  testme testvalue`

**Comment by sunshine69** [comment]
Thanks looks like it works
