### ISSUE TITLE
RIPEMD160 removed in cryptography 2.1

### ISSUE THREAD

**Issue by jwineinger** [fugue/credstash#201]
Whirlpool and RIPEMD160 were removed in cryptography 2.1 (https://cryptography.io/en/latest/changelog/#v2-1) which causes credstash to break due to:

https://github.com/fugue/credstash/blob/master/credstash.py#L55-L56

```
  File "/usr/local/lib/python2.7/site-packages/credstash.py", line 54, in <module>
    'RIPEMD': hashes.RIPEMD160,
AttributeError: 'module' object has no attribute 'RIPEMD160'
```

**Comment by marcfielding1** [comment]
Yeah I'm hitting this in a circleCI build, oddly enough when I install on my Mac it works fine.

**Comment by a12k** [comment]
@marcfielding1 Same here, but as soon as I updated my cryptography it started breaking. I just had an old version. There's a pull request up to remove support for RIPEMD and WHIRLPOOL, fyi.

**Comment by glyph** [comment]
The PR in question is #178.
