### ISSUE TITLE
Is Credstash still being maintained?

### ISSUE THREAD

**Issue by CaseyLabs** [fugue/credstash#236]
Just wondering if this project has been abandoned, or if there are any active maintainers?

I ran into a small bug that was resolved by a PR last August, but hasn't been merged yet. Is Crestash still active, or is it no longer safe to use in production?

https://github.com/fugue/credstash/issues/218
https://github.com/fugue/credstash/pull/219

**Comment by cheethoe** [comment]
Feels pretty abandoned... feels bad.

**Comment by mike-luminal** [comment]
Hey guys, I'm the new maintainer within Fugue, I apologize for the radio silence. I'm working on reviewing and merging PRs.

**Comment by corrjo** [comment]
Thanks for the release @mike-luminal! It looks like it hasn't been uploaded to pypi yet though.

**Comment by mike-luminal** [comment]
> Thanks for the release @mike-luminal! It looks like it hasn't been uploaded to pypi yet though.

🤦‍♂ Thanks for pointing it out, I will make it happen.
