### ISSUE TITLE
Release 1.16.0 to pypi

### ISSUE THREAD

**Issue by 0xMAYANK** [fugue/credstash#248]
Credstash package is still on `1.15.0`, we could use some of the new features.
Please release `1.16.0` to pypi.

**Comment by mike-luminal** [comment]
Hello, sorry for the delay, it took a little while to get permissions on the `credstash` PyPi project. v1.16.1 has been released with fixes for v1.16.0 and is available on PyPi: https://pypi.org/manage/project/credstash/release/1.16.1/
