### ISSUE TITLE
Credstash.log is created in current directory even when --log-file is provided.

### ISSUE THREAD

**Issue by ElayneB** [fugue/credstash#274]
Running into a problem where credstash creates the file `credstash.log` in the current directory even if I pass it the `--logfile` argument. E.g.
`credstash --log-file '/tmp/credstash.log' --table $CREDSTASH_TABLE --region $AWS_REGION getall --format dotenv` creates the file `/tmp/credstash.log` but it also creates a file `credstash.log` in the current working directory.

**Comment by mike-luminal** [comment]
Resolved in #279,
