### ISSUE TITLE
V 1.16.2 breaks on AWS Lambda

### ISSUE THREAD

**Issue by samc0de** [fugue/credstash#286]
I am using credstash in an AWS Lambda function (Python). The above mentioned release (which adds logging) tries to create a new file in the current directory, which is /var/task/, and is readonly, and hence fails.

![image](https://user-images.githubusercontent.com/908286/78225051-28dc1200-74e7-11ea-88a0-aeb329b2a837.png)

**Comment by mike-luminal** [comment]
Hi @samc0de, thanks for the issue and PR. This issue was fixed in #280 , which removes logging when `credstash` is used as a lib.
