### ISSUE TITLE
Allow usage of multiple AWS credential profiles

### ISSUE THREAD

**Issue by bhourigan** [fugue/credstash#48]
Right now it appears to only work with the 'default' profile in ~/.aws/credentials, it'd be nice to support multiple credentials for those of us who have many AWS accounts to work with.

**Comment by spscacyost** [comment]
```
[dev]
aws_access_key_id = TROLLOLOLOLOLOLOL
aws_secret_access_key = TROLLOLOLOLOLOLOL
[prod]
aws_access_key_id= TROLLOLOLOLOLOLOL
aws_secret_access_key= TROLLOLOLOLOLOLOL
```
and then 
for example:
export AWS_PROFILE=dev ( or AWS_PROFILE=prod )
ala https://blogs.aws.amazon.com/security/post/Tx3D6U6WSFGOK2H/A-New-and-Standardized-Way-to-Manage-Credentials-in-the-AWS-SDKs
seems to work ?

**Comment by alex-luminal** [comment]
That works great! I'll add a note to the README
