### ISSUE TITLE
Unable to import module '[module_name]': /var/task/Crypto/Cipher/_AES.so: invalid ELF header

### ISSUE THREAD

**Issue by nihakue** [fugue/credstash#58]
I'm trying to use credstash to retrieve credentials in an aws lambda function e.g.
```python
from credstash import getSecret
password = getSecret(USERNAME)
```

But I'm getting the following error when the function runs:
```
Unable to import module '[module_name]': /var/task/Crypto/Cipher/_AES.so: invalid ELF header
```

I'm not sure what the cause is. My lambda function lives in a virtualenv, and when I deploy I copy the contents of lib/python2.7/site-packages/ into the zip. Do you have any ideas?

**Comment by alex-luminal** [comment]
Did you build your virtualenv on a linux box? The Invalid ELF header error makes me think that the openssl shared library is messed up

**Comment by nihakue** [comment]
Whoops. I'll bet that's what it was. I'll check right now.

**Comment by nihakue** [comment]
Yep, that was all it was. Sorry to trouble you!

**Comment by Breeze773** [comment]
Sorry to bring this one back up, but I am relatively new to python.  I am trying to use credstash in lambda function and am getting this error as well.  How do I un mess up my openssl?  I am working with python 2.7.10 on OS X, by the way.
Thanks

**Comment by ElliotG** [comment]
Similarly, also have the exact same issue.

**Comment by alex-luminal** [comment]
The python openssl library brings a shared library along with it. You want to make sure you build your virtualenv on a linux box. If you build it on OSX, the shared library will be build for OSX, not for linux.

**Comment by Breeze773** [comment]
Thanks, @alex-luminal.  I wound up doing that but am taking it a step further and using a docker container for this.  That gets me a linux os for packaging with the shared lib but still keeps the development local.

**Comment by iamaziz** [comment]
Thanks a million @alex-luminal saved my day!
