### ISSUE TITLE
Support for multiple AWS profiles

### ISSUE THREAD

**Issue by Caid11** [fugue/credstash#61]
It'd be great if we could pass in profile names to credstash method parameters, rather than only being able to specify the profile via the environment variable. This would allow users to take advantage of multiple AWS profiles when they are using credstash as a Python module.

Boto3 supports the generation of sessions based on profile names, so the enhancement is very easy to implement and doesn't affect base functionality in any way. I've actually already implemented it in my own project [here](https://github.com/Caid11/ClipStash/blob/master/credstash.py) (although my implementation doesn't respect the environment variable). 

If the idea is alright with you, I'd be willing to put my own changes (modified to respect the environment variable) in as a pull request. Thanks for your time!

**Comment by alex-luminal** [comment]
Pull requests welcome!

**Comment by Caid11** [comment]
Cool, will put one in!

**Comment by alex-luminal** [comment]
Just merged the PR. I'll push a new release to PyPi sometime this week.

**Comment by bhourigan** [comment]
This is fantastic, thank you! There is another way to use alternate profiles as well: https://github.com/fugue/credstash/issues/48

However, this introduced a bug where it will only communicate with us-east-1.

Example:

```
$ # credstash -r us-west-1 -t foobar list
Traceback (most recent call last):
  File "/usr/local/bin/credstash", line 9, in <module>
    load_entry_point('credstash==1.9.0', 'console_scripts', 'credstash')()
  File "/usr/local/bin/credstash.py", line 485, in main
    credential_list = listSecrets(region=region, table=args.table)
  File "/usr/local/bin/credstash.py", line 171, in listSecrets
    ExpressionAttributeNames={"#N": "name"})
  File "/usr/local/lib/python2.7/dist-packages/boto3/resources/factory.py", line 455, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/boto3/resources/action.py", line 79, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 407, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the Scan operation: User: arn:aws:sts::NNNNNNN:assumed-role/foobar/i-xxxxxxx is not authorized to perform: dynamodb:Scan on resource: arn:aws:dynamodb:us-east-1:NNNNNNN:assumed:table/foobar
```

Note the string us-east-1 in the dymamodb ARN.

**Comment by Caid11** [comment]
Huh, I'll see if I can get that fixed.

**Comment by Caid11** [comment]
@bhourigan I can't seem to reproduce the bug. I've managed to use the default `credential-store` table as well as a non-default named table in us-west-2.

I'll keep trying, though. In the meantime, are there any other details you can provide that might help?

**Comment by bhourigan** [comment]
@Caid11 I can reproduce it reliably - so feel free to leverage me for additional debugging information as needed. In this case I'm using it on an EC2 host that's assigned an IAM role. I don't have ~/.aws or any credentials configured locally. I double checked and my command line parameters are exactly as quoted in my previous comment, excluding my account specific information.

**Comment by bhourigan** [comment]
@Caid11 I added some print statements to credstash.py which illustrates the problem I'm running into.

Debug output
```
[root@ip-172-30-33-76 bin]# credstash -r us-west-1 list
args.region us-west-1
region us-east-1
Traceback (most recent call last):
  File "/usr/local/bin/credstash", line 9, in <module>
    load_entry_point('credstash==1.9.0', 'console_scripts', 'credstash')()
  File "/usr/local/bin/credstash.py", line 487, in main
    credential_list = listSecrets(region=region, table=args.table)
  File "/usr/local/bin/credstash.py", line 171, in listSecrets
    ExpressionAttributeNames={"#N": "name"})
<trimmed>
```

Command used: `credstash -r us-west-1 list`

My patch:
```
--- credstash.py.orig	2016-01-15 01:59:04.177148856 +0000
+++ credstash.py	2016-01-15 02:03:28.414351558 +0000
@@ -471,11 +471,13 @@

     args = parsers['super'].parse_args()

+    print "args.region %s" % args.region
     try:
         region = args.region
         boto3.resource('dynamodb')
     except botocore.exceptions.NoRegionError:
         region = DEFAULT_REGION
+    print "region %s" % region

     if "action" in vars(args):
```

By the way, while digging into this I found an anomaly in the listSecrets() function. 

I see the boto session handle is initialized as:
```
    session = boto3.Session(profile_name=profile_name)
```

Checking the [boto3 session documentation](http://boto3.readthedocs.org/en/latest/reference/core/session.html) it seems the region is set during the session initialization. However, the *resource* initialization gets region_name passed. I don't see this as a valid parameter according to the [boto3 resource documentation](http://boto3.readthedocs.org/en/latest/reference/core/resources.html)

**Comment by Caid11** [comment]
@bhourigan Ah, I tested it on my personal machine (a.k.a. a machine with no IAM credentials and a boto config file), so that might be the problem. I think I know how to fix the bug; I'll test it tomorrow and submit a PR if it works. 

On the precedence of profiles, I believe that method parameters override all other parameters, so if you create a session with a region, then specify a region as a parameter in a method called on that session, that parameter would override the session parameter (the documentation [here](http://boto3.readthedocs.org/en/latest/guide/configuration.html#configuration-sources) kind of implies this, but doesn't explicitly state it).

On `region_name` not being present in the documentation, I actually noticed that too. It's a pretty common parameter in many other boto methods (clients, sessions, etc.), so I think it might just have been overlooked. However, it might be good to suggest switching `region_name` to the `Session` method just so credstash conforms to the documentation.

**Comment by bhourigan** [comment]
> @bhourigan Ah, I tested it on my personal machine (a.k.a. a machine with no IAM credentials and a boto config file), so that might be the problem. I think I know how to fix the bug; I'll test it tomorrow and submit a PR if it works.

Thank you!

**Comment by Caid11** [comment]
@bhourigan Found the issue. In the main function, they attempt to check if the region passed to credstash will actual work here:
```python
try:
    region = args.region
    boto3.resource('dynamodb')
except botocore.exceptions.NoRegionError:
    region = DEFAULT_REGION
```
This is great, except they don't actually use the `region_name` parameter when they are checking the region, so, if there is no region defined in an environment variable or config file, it always falls back to `us-east-1` (like we were seeing). It looks like someone already opened a PR to fix this, so we should be good to go!
