### ISSUE TITLE
[Bug] Get/Put binary files

### ISSUE THREAD

**Issue by CarsonF** [fugue/credstash#73]
I'm trying to store a binary file, but I get this error when I try to _put_:

```
credstash put: error: argument value: invalid value_or_filename value: '@/Users/Carson/.keystore'
```

This works fine with a [PHP port](https://github.com/gmo/credstash-php) I've been working on... :grin:

So if I _put_ with PHP and try to _get_ with Python I get this error:

```
  File "/usr/local/bin/credstash.py", line 299, in getSecret
    plaintext = plaintext.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 0: invalid start byte
```

Thoughts?

**Comment by alex-luminal** [comment]
+1

I know of at least one person who worked around this by base64-encoding binaries that he was sticking in credstash, but that sucks. We should actually fix it. We could either store another attribute that the stored value is a binary and so not to decode it as utf-8, or do something smarter about encoding. 

I'm traveling at the moment, and wont have time to get on this until I get back. If anyone wants to cut a PR in the meantime, it would be super appreciated :)

**Comment by vccabral** [comment]
+1
I'd love to make a more significant contribution. I might need a bit of hand holding :(

**Comment by spallem** [comment]
Also there seems to be a padding issue with the secret. The secret has to be length multiples of 16. Is there a flag to specify padding character?

**Comment by artburkart** [comment]
I've opened a PR that may serve as an example of how this might be tackled? I'm unsure, would love to discuss further. Thanks!
