### ISSUE TITLE
Encrypt AWS credentials 

### ISSUE THREAD

**Issue by iamhasibrahman** [fugue/credstash#74]
Awesome tool! 

Question -- your tool will utilise AWS secret & access key .. How do we encrypt them? We wouldn't leave them either on config file or even as environment variable?

Please advise. Thanks.

**Comment by dom-at-luminal** [comment]
@iamhasibrahman, the canonical way to store SK/AK pairs is indeed config files or environment variables. It's good practice to limit the IAM user's permissions to the minimum required to do the job.

If you're really uncomfortable with storage of SK/AK pairs on a local device, you could use a small instance (t2.nano should be plenty) with an IAM Role assigned to it. When you do that, `credstash` will seek credentials from the instance metadata service. AWS will do automatic credential rotation and you will not have to manage them at all.

More on IAM Roles: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html

**Comment by iamhasibrahman** [comment]
Here is what I understand ---

There is obviously no way you can encrypt the main AK/SK which Credstash require ...

You are advising to store them in small instance (which is a good idea) but how it will work when Credstash will run on external source system ??? 

As in example --- 

RHEL Server (outside of AWS) - we capture logs from this using Fluentd. 

Fluentd sends logs to Kinesis, which is being picked up by KCL application running on ec2 instance. 

Did I just confuse you? 

another question - if I have 10 instance of ec2 fleet, I would have to run Credstash in each one of them?

**Comment by alex-luminal** [comment]
If you're running `n` EC2 instances, and they each need to access secrets on stored with credstash, they should each run a copy of credstash (or one of the libraries that implements credstash's scheme).

**Comment by dom-at-fugue** [comment]
> You are advising to store them in small instance

Sort of, though there's a clarification that's important there. Assigning an IAM Role to an instance means that it has credentials stored in the instance metadata service and rotated on your behalf by Amazon. You would not personally act to "store" credentials anywhere. You'd never touch them. Effectively, giving an instance an IAM Role means that programs running on the instance can do things with the AWS API that the role allows.

> RHEL Server (outside of AWS)

In this case, there is no instance metadata service, so you would have to fall back to some other means, such as a designated configuration file or environment variable. Remember that `credstash` uses the `boto` library, so the precedence for credentials is the same:

 * Environment variables
 * Shared credential file (~/.aws/credentials)
 * AWS config file (~/.aws/config)
 * Assume Role provider
 * Boto2 config file (/etc/boto.cfg and ~/.boto)
 * Instance metadata service on an Amazon EC2 instance that has an IAM role configured.

> if I have 10 instance of ec2 fleet, I would have to run Credstash in each one of them?

You'll need to run `credstash` to store and retrieve secrets, so any instances that would need to do so must have it installed and runnable.

Good luck with your project!

**Comment by iamhasibrahman** [comment]
Problem with designated config file is that it's not really encrypted .. And anyone with the access to the machine can access it .

**Comment by iamhasibrahman** [comment]
In regards to Assume Role Provider ---

We need to write code to make it work on say server running outside of AWS??? How would that work? Can you please explain?

**Comment by dom-at-fugue** [comment]
> Problem with designated config file is that it's not really encrypted .. And anyone with the access to the machine can access it .

That's not necessarily true. The files in `~/.aws/` are stored in a user's home directory, so they can be confidential to a user. If someone has `root`/sudo access to the machine, they can read other users' home directories, but now there's a more fundamental problem that `credstash` cannot fix for you. If segregation of access is important to your use of `credstash`, I recommend you give each user their own machine, or at least their own accounts on a shared machine and limited privileges so that they cannot read each others' files.

For more information, I recommend watching @alex-luminal's talk, "Managing Secrets at Scale": https://vimeo.com/147644113

**Comment by iamhasibrahman** [comment]
In regards to Assume Role Provider ---

We need to write code to make it work on say server running outside of AWS??? How would that work? Can you please explain?

**Comment by dom-at-fugue** [comment]
@iamhasibrahman see the boto docs here: http://boto3.readthedocs.org/en/latest/guide/configuration.html#assume-role-provider

Best of luck with your project.
