### ISSUE TITLE
New Getall Export Type

### ISSUE THREAD

**Issue by chaseconey** [fugue/credstash#76]
I was wondering if it would be possible to put in a feature request to add an additional getall format.

I would love to support the key/value format supported by [this library](https://github.com/vlucas/phpdotenv). There are quite a few frameworks that support this format, would definitely be a huge win.

Example format:

```
DB_HOST=localhost
DB_PORT=3306
DB_USERNAME=root
DB_PASSWORD=root
```

**Comment by alex-luminal** [comment]
Just merged this in #106. will be in the next release that goes to pypi today or tomorrow
