### ISSUE TITLE
How do I use this from AWS?

### ISSUE THREAD

**Issue by rprakashg** [fugue/credstash#78]
I'm wondering how i would use this from AWS as example I have a Lambda function that needs to pull in credentials to connect to an RDS instance

**Comment by alex-luminal** [comment]
you'll need your lambda function to have its IAM role configured to be able to hit KMS and dynamodb. Beyond that, you can bundle up credstash with your lambda function and invoke it when you need it.

**Comment by alex-luminal** [comment]
closing this for now. feel free to reopen if I didnt answer your question
