### ISSUE TITLE
ansible with credstash

### ISSUE THREAD

**Issue by SydOps** [fugue/credstash#82]
I am little confused where the key/value to be decrypted. 

I currently set KMS key and created dynamoDB by credstash. I can run `credstash get my-github-password` to get the decrypted values directly on my laptop.

Now I need run ansible playbook from my computer. So when ansible code go with lookup 

     -  debug: msg="Credstash lookup! {{ lookup('credstash', 'my-github-password') }}"

Is the credstash command running from the remote server or run from my computer to get the decrypted value?

I need think about what policy to be assigned to my local account or to the IAM role for that instance.

**Comment by SydOps** [comment]
After testing, seems the permission (or aws policy) should be applied to ec2 instance's IAM role, because it is not safe to put aws api key in .boto or .aws in each instance

**Comment by rilindo** [comment]
It runs off the remote server. So at the very lease, the role needs to be able to:

1. Talk to KMS
2. Talk to DynamoDB
