### ISSUE TITLE
Changeable Schema

### ISSUE THREAD

**Issue by DanishKhakwani** [fugue/credstash#85]
Hi, I would like to see this tool to have a changeable schema.

For instance, I would like to store the keys based on the environment and project.
I can do that with providing context but if the key name is same for a different project then I don't have any other option currently.

For instance:
credstash put keySL value1 environment=stg project=SL
credstash put keySL 1value environment=stg project=DD
ERROR: authKeyIdTRDSL version 0000000000000000001 is already in the credential store. Use the -v flag to specify a new version

**Comment by alex-luminal** [comment]
Have you looked at the `-t` flag? you can have multiple independent DDB
tables. So you can have different tables for different environments,
applications, etc. This may fit your needs.

**Comment by DanishKhakwani** [comment]
I did think of having multiple tables. But having so many projects + at least 3 environments would create so many tables which doesn't look like a good solution to me.

For now I am going to name the keys ENV_PROJECT_KEYNAME to make sure the key names are unique.
