### ISSUE TITLE
KMS ERROR: Could not generate key using KMS key alias/credstash

### ISSUE THREAD

**Issue by ericgoedtel** [fugue/credstash#86]
Hello,

Working on getting this running for the first time and I seem to be stuck. I have done the following:
1. Created a DynamoDB table using `credstash setup`
2. Created a KMS key with an alias of "credstash" and assigned my API user to use the key
3. Attempted to run `credstash put foo bar`
4. Receive the following error: `KMS ERROR: Could not generate key using KMS key alias/credstash`

I thought that it might have to do with `alias/credstash` so I also tried: `credstash put foo bar -k credstash` but received the same error with the different alias name.

I seem to be missing something fundamental, here, as I imagine this should just work.

**Comment by alex-luminal** [comment]
I would double check the permissions you have on your KMS key. The user/role that is doing `credstash put foo bar` needs to be able to use the KMS key.

**Comment by ericgoedtel** [comment]
Yep, I just tried running it manually:

`aws --profile credstash kms generate-data-key --key-id deadbeef-3786-dead-beef-deadbeef7056 --number-of-bytes 64 --region us-east-1`

`A client error (DisabledException) occurred when calling the GenerateDataKey operation: arn:aws:kms:us-east-1:123456789012:key/deadbeef-3786-dead-beef-deadbeef7056 is disabled.`

I'm not sure *why* it is disabled since I created it through the console but that is not a question for you :).

Thanks for the prompt response!

**Comment by alex-luminal** [comment]
closing this for now

**Comment by ericgoedtel** [comment]
Sorry if this reopens--but just because other folks might not be familiar with KMS--[here is how you enable a key :)](https://cloud.githubusercontent.com/assets/3443258/16487763/c3a940fa-3e9a-11e6-8ba3-b21007de0e7e.png)
