### ISSUE TITLE
Can't store strings that begin with -

### ISSUE THREAD

**Issue by bo01ean** [fugue/credstash#88]
When you try to store a value that begins with a - program does not execute as expected.

python --version: Python 2.7.11
uname -a: Darwin ip-192-168-128-62.ec2.internal 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64

`credstash put a.b.c "-Putanythinginherethatstartswitha-"
usage: credstash put [-h] [-k KEY] [-v VERSION] [-a]
                     credential value [context [context ...]]
credstash put: error: too few arguments`

Please advise.

**Comment by bo01ean** [comment]
I was able to work around this by sending the value via STDIN:

`echo "-secret" | credstash put a.b.c -`

**Comment by bo01ean** [comment]
Seems this is related to the library in use:
https://bugs.python.org/issue9334

**Comment by nasskach** [comment]
This is not a big issue, you need simply use a double dash (--) like this :
```bash
credstash put -- a.b.c -Putanythinginherethatstartswitha-
```

**Comment by artburkart** [comment]
Per @nasskach's comment, I would argue this issue can be closed. Using `--` is pretty standard for most command line tools when dealing with args that contain leading `-`s.

**Comment by bo01ean** [comment]
Using -- appends a newline to the value being stored as well, which may be a whole other bug

**Comment by artburkart** [comment]
Hmmm, I only see that behavior when using the `echo` method:

```
$ echo -secret | credstash put -a a.b.c -
$ credstash get a.b.c
-secret

```

vs

```
$ credstash put -a -- a.b.c -secret
$ credstash get a.b.c
-secret
```

**Comment by bo01ean** [comment]
correct,  |, not --.

I am going to close this, as there is few workarounds. Just have to use -- if you don't want extra newlines.

Not sure if a new issue for the extra newline on pipe is needed :)
