### ISSUE TITLE
Cross-account access

### ISSUE THREAD

**Issue by artburkart** [fugue/credstash#89]
I struggled with setting up cross-account access for a little while. I thought it would be useful if it were documented somewhere, but I'm not sure where it would go.

[This tutorial was super helpful](http://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html).

In short:

- AccountA contains protected data and you want to grant AccountB access to it
- Create an IAM role in AccountA with the regular permissions you'd give it to access the relevant DynamoDB and KMS resources (from the [README](https://github.com/fugue/credstash/blob/318ffe151798c2a78334385abf04be4ee56cde44/README.md))

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "kms:Decrypt"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:kms:us-east-1:AccountA:key/b535d0f6-299f-4499-bf69-c19c63d822b1"
        },
        {
            "Action": [
                "dynamodb:GetItem",
                "dynamodb:Query",
                "dynamodb:Scan"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:dynamodb:us-east-1:AccountA:table/credential-store"
        }
    ]
}
```

- Give the IAM role a Trust Relationship that looks like:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::AccountB:root"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```
- In my case, I then created an IAM role (instance profile) in AccountB with the following permissions:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "sts:AssumeRole",
            "Resource": "arn:aws:iam::AccountA:role/name-of-role-from-accounta"
        }
    ]
}
```

- I then started an instance in AccountB with the new role that had the AssumeRole policy and executed credstash thusly: 

```
credstash --arn arn:aws:iam::AccountA:role/name-of-role-from-accounta get some_key_that_should_be_there
```

**Comment by alex-luminal** [comment]
I added this to the credstash wiki: https://github.com/fugue/credstash/wiki/Setting-up-cross-account-access

Thanks for writing this up
