### ISSUE TITLE
STS Assume Role support

### ISSUE THREAD

**Issue by kiwifellows** [fugue/credstash#90]
I had an idea to provide STS Assume Role support so you can pass the STS credentials (AccessKey, Secret, Session Token) along as parameters to credstash. This way will be a way of storing credentials in the STS account.

**Comment by alex-luminal** [comment]
you can use the `-n` flag to pass an IAM role arn to credstash and it will do the call to STS to get creds for you.

**Comment by alex-luminal** [comment]
closing this for now. feel free to re-open
