### ISSUE TITLE
Recommended workflow in multiple environments?

### ISSUE THREAD

**Issue by machira** [fugue/credstash#95]
Hey! I would like to use credstash to store secrets in different environments (staging, qa, prod). Initially, I thought I could use the context, and credstash would handle creating the duplicate rows and retrieving the correct credential given context. But after spending a bit of time seeing how the application works, I realize that this is not correct, and setting  DBPASSWORD context=qa, then DBPASSWORD context=prod would cause a collision. 
The present idea is to use different tables for each environment. This seems to be working, but I am wondering if there is a more recommended approach. 
Thanks for this awesome utility!

**Comment by richardnbanks** [comment]
Hi,

The way I'm looking at solving this is through key naming. So I would get information by running one of following depending on the environment:

credstash -k DevKey get app.db.pass.dev
credstash -k QAKey get app.db.pass.qa
credstash -k ProdKey get app.db.pass.prod

As I understand it, the context is stored separately from the credential-name which must be unique.

**Comment by machira** [comment]
Thanks for responding richard!

**Comment by alex-luminal** [comment]
This is a great approach. Thanks for responding.

Going to close this ticket for now, but feed free to reopen if you want to discuss it more.
